### ISSUE TITLE
Toggl can't time

### ISSUE THREAD

**Issue by LoveOctocat** [benhughes/of-start-toggl-timer#6] opened 2021-03-24 09:00 UTC
Mac: 3.11.6 (v149.12.0) Mac OmniFocus, which was updated yesterday.
iOS: 3.11.5 Pro (v148.9.0)

Using OmniFocus today, I found that I can't start the timer anymore.

If I delete the plugin and reinstall https://github.com/benhughes/OmniToggl/releases version 1.1.1, OmniFocus for Mac still does not work. iOS can start the timer, but cannot end it. On the iOS side, after manually turning off Toggl timer, iOS OmniFocus is also not available.

**Comment by benhughes** [comment] 2021-03-24 09:25
Ok, I think this may be an issue with the latest OmniFocus. I've had issues with the new version I'm testing and hoped it was an issue with the new version, not OmniFocus. Will investigate and raise a bug.

**Comment by LoveOctocat** [comment] 2021-03-24 10:25
Thank you for providing this tool. It has been a great help to me.

**Comment by bsidecode** [comment] 2021-03-25 17:47
FYI seems to be working again in 3.11.7 beta, possibly due to your bug report :). Thanks for the great tool!

**Comment by benhughes** [comment] 2021-03-25 18:30
That's good to hear, even in my tests it's a bit on and off if it works or not so let me know if it plays up again. I'll give the beta a download.

**Comment by benhughes** [comment] 2021-03-25 18:33
Oh saying that. I got a reply.

>This is a regression we are aware of and should have fixed in our next update. 

So hopefully they'll have an official build out soon

**Comment by jornnyliu** [comment] 2021-03-28 03:23
Thanks Benhughes!

I met same question and I hope it will be works again.

Many thanks to Benhughes OmniToggle is best time manage tools to me.

**Comment by manipeaci** [comment] 2021-04-06 18:54
I am having difficulties as well. I can only start / stop a timer once and then I need to restart omnifocus.

(works as normal on iOS though!)

**Comment by benhughes** [comment] 2021-04-07 13:47
Yeah it's a known bug in OmniFocus which is frustrating as there release cadence is not great. Here's an email I received from them with instructions on how to get the beta build:

---

Sorry for the trouble here, but thanks for getting in touch!

This is a regression we are aware of and should have fixed in our next update.

We do have test builds available for this next update, which you can try out. However, since you are currently using OmniFocus from the Mac App Store, you can't just seamlessly use a test build for the moment. This is because release/test builds from our website are treated as a separate app (different bundle identifier) as builds of OmniFocus from the Mac App Store. Therefore, to use the test builds, you'd be setting up the app from scratch. It wouldn't have any of your existing preferences, linked folders you may use for plug-ins, etc.

That said, if you do want to try out a test build, you can grab a build here:
<https://omnistaging.omnigroup.com/omnifocus/>

As part of all this I should mention that, even if you purchased OmniFocus from the Mac App Store, you could now switch to using non-Mac App Store builds. This is due to a change in our app handles licensing. You'd just need to make sure your existing purchase of the app is registered with your Omni Account, which you'll sign into when setting up the app. The advantage of using builds direct from us is it does give you greater flexibility to switch between release and test builds, or even revert back to older builds. If you have any more questions on this, just let me know.

And of course, hopefully we'll have this update ready to officially ship soon, so we can get this fix out the door!

If you have any additional suggestions, questions or concerns, please don't hesitate to let me know. We really appreciate your support!

**Comment by benhughes** [comment] 2021-04-16 16:32
The new version has hit the mac app store and seems to work as it used to so closing this now. Thanks for reporting.

**Closed as completed by benhughes** 2021-04-16 16:32 UTC
